"""
MI IDEA SERÍA LEER EL EXCEL, Y SER CAPAZ DE CALCULAR LO QUE LE DEBE EL UNO AL OTRO, LO QUE GASTO CADA UNO EN EL MES, ORGANIZAR SOBRE LO QUE MÁS SE COMPRO Y LO MÁS CARO,
ORGANIZAR SEGÚN LAS CATEGORÍAS, ORGANIZAR SEGÚN PERSONAS
"""


class Archivo:
    
    def __init__(self):
        pass