"""
MI IDEA SERÍA LEER EL EXCEL, Y SER CAPAZ DE CALCULAR LO QUE LE DEBE EL UNO AL OTRO, LO QUE GASTO CADA UNO EN EL MES, ORDENAR SEGUN PRECIOS,
ORDENAR SEGÚN CATEGORÍAS, ORDENAR SEGUN PERSONAS.
FILTRAR SEGÚN LO MISMO QUE QUIERO ORDENAR
"""

import pandas as pd


class Archivo:
    
    def __init__(self):
        pass