"""
LA IDEA VA A SER TENER UN EXCEL POR CADA MES, EN DONDE EN CADA WORKSHEET
VAYAN LOS DÍAS. LAS CATEGORIAS VAN A SER: CANTIDAD, TIPO, PRECIO, PERSONA, CATEGORÍA
PARA GARANTIZAR EL CORRECTO ORDEN.
LA IDEA DEL SCRIPT DE PYTHON VA A SER TENER UNA MEJOR VISUALIZACIÓN
DE LA INFORMACIÓN Y CALCULAR RÁPIDAMENTE LO QUE DEBE EL UNO AL OTRO.
ADEMÁS, SERÍA BUENO AÑADIR UN WORKSHEET DE GASTOS PERSONALES, QUE NO
VAYAN INCLUIDOS EN EL CÁLCULO FINAL, YA QUE SERÍA PERSONAL, VALGA LA
REDUNDANCIA.
ADEMÁS, SERÍA BUENO REPLICAR LAS MISMAS COLUMNAS EN TODOS LOS WORKSHEETS

"""

from functions import generador_archivos, generador_columnas

def main():
    variable = generador_columnas()
    
    
if __name__ == '__main__':
    main()
    print("HOLA")